project:
  type: book
  

book:
  title: "I Optimal Designs for Experiments in R"
  author: "Stu and Company"
  date: "3/2/2025"
  chapters:
    - index.qmd
    - 05_preface.qmd
    - 10_intro_to_r.qmd  
    - references.qmd
  sidebar:
    style: docked
    search: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  pdf:
    documentclass: scrreprt
